version: "3"

tasks:
  build:darwin:
    cmds:
      - GOOS="darwin" GOARCH="amd64" go build -o ./bin/darwin/tempura main.go
    silent: true

  build:linux:
    cmds:
      - GOOS="linux" GOARCH="amd64" go build -o ./bin/linux/tempura main.go
    silent: true
